
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-dev-cluster-1
  region: ap-northeast-2

vpc:
  id: "vpc-0d4646df276b9d89e"
  subnets:
    private:
      us-west-2a:
          id: "subnet-0ff156e0c4a6d300c"
      us-west-2c:
          id: "subnet-0426fb4a607393184"
    public:
      us-west-2a:
          id: "subnet-0153e560b3129a696"
      us-west-2c:
          id: "subnet-009fa0199ec203c37"


nodeGroups:
  - name: dev-ng-1
    instanceType: t2.medium
    desiredCapacity: 3
    volumeSize: 20
    ssh:
      allow: true
