apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-api-deployment
  namespace: dev
  labels:
    app: dev-member-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-member-api
  template:
    metadata:
      labels:
        app: dev-member-api
    spec:
      containers:
      - name: member-api
        image: -.dkr.ecr.ap-northeast-2.amazonaws.com/member-api:16
        ports:
        - name: tcp
          containerPort: 8080
