# create configmap for cwagent config
apiVersion: v1
data:
  # Configuration is in Json format. No matter what configure change you make,
  # please keep the Json blob valid.
  cwagentconfig.json: |
    {
        "agent": {
            "region": "ap-northeast-2"
        },
      "logs": {
        "metrics_collected": {
          "kubernetes": {
            "cluster_name": "dev-api-deployment",
            "metrics_collection_interval": 60
          }
        },
        "force_flush_interval": 5
	"endpoint_override": "logs.ap-northeast-2.amazonaws.com"
  },
        "metrics": {
            "metrics_collected": {
                "statsd": {
                    "service_address": ":80"
                }
            }
        }
    }
kind: ConfigMap
metadata:
  name: cwagentconfig
  namespace: amazon-cloudwatch
